### ISSUE TITLE
CHECK YOUR SERVER SECURITY

### ISSUE THREAD

**Issue by excitedbox** [OliverKillane/Dungeon-Escape-Python#1]
I found an issue with your repl on your NN project. If you stop the editor you get full shell access to your server. using pip people can then install anything they want. sadly you don't list any contact info so I could only message you like this.

**Comment by OliverKillane** [comment]
Hi there,

Thank you for the email. As the repl is hosted for free on repl.it, I have
no control over the way it is set up.

Replit creates a new temporary instance for every user running the repl,
and hence any changes a user makes to that instance will have no effect.

If you can find some way to create permanent changes, I suggest you report
it to https://repl.it/bugs/ .

Have a good day!

Yours sincerely
Oliver Killane.

**Comment by excitedbox** [comment]
Ahh ok I didn't look that deeply into it but I only tested that I could get pip to install python packages and then posted here. I guess they are spinning up virtual machines so there shouldn't be anything to worry about. With the number of python installations it looked more like a home setup so I thought there might be config files with stored passwords in there. If you have any kind of web service configs with DB passwords in clear text format you should still be careful.
